### ISSUE TITLE
boost dependency?

### ISSUE THREAD

**Issue by shakfu** [ndarray/ndarray#102]
In `ndarray_fwd.h` the following boost headers are included

```c++
#include <boost/type_traits/is_const.hpp>
#include <boost/type_traits/add_const.hpp>
#include <boost/type_traits/remove_const.hpp>
#include <boost/mpl/bool.hpp>
```

I'm assuming this means that `ndarray` depends on parts of `boost`.

Looking at the title of the recent release, are there any plans to remove this dependency in this future?

**Comment by TallJimbo** [comment]
Not in the foreseeable future - the library is mostly in maintenance mode now, as I just don't have the time to make larger changes.

**Comment by shakfu** [comment]
@TallJimbo 

Understood. Thanks for your clarification.
