### ISSUE TITLE
dimensions > 8

### ISSUE THREAD

**Issue by hgkamath** [ndarray/ndarray#39]
I see that the dimensions are limited to 8, in part because of make_vector, and initialization. Can some idea like the below allow ndarray to extend to unlimited dimensions. In the below example when N&gt;4, C1&lt;N&gt; uses C1&lt;4&gt; as a member. Basically, one foregoes the expression template optimizations for the higher dimensions.

```
#include <iostream>
#include <vector>


void printvect(std::vector<int> &v1) {
  for (auto c : v1) std::cout << c << " "  ; 
}

template <size_t N> class C1 ;
template <> class C1<1> {
  public:
  std::vector<int> v1;
  C1() : v1{1} {};
  void func1() { std::cout << "C1 1: " ; printvect(v1) ; std::cout << std::endl ;}
  C1<1> operator+(C1<1> &c2){
    C1<1> r;
    r.v1[0]=v1[0]+c2.v1[0];
    return r;
  }
};
template <> class C1<2> {
  public:
  std::vector<int> v1;
  C1() : v1{1,2} {};
  void func1() { std::cout << "C1 2: " ; printvect(v1) ; std::cout << std::endl ;}
  C1<2> operator+(C1<2> &c2){
    C1<2> r;
    r.v1[0]=v1[0]+c2.v1[0];
    r.v1[1]=v1[1]+c2.v1[1];
    return r;
  }
};
template <> class C1<3> {
  public:
  std::vector<int> v1;
  C1() : v1{1,2,3} {};
  void func1() { std::cout << "C1 3: " ; printvect(v1) ; std::cout << std::endl ;}
  C1<3> operator+(C1<3> &c2){
    C1<3> r;
    for(size_t iter1=0; iter1<3; ++iter1)
      r.v1[iter1]=v1[iter1]+c2.v1[iter1];
    return r;
  }
};
template <> class C1<4> {
  public:
  std::vector<int> v1;
  C1() : v1{1,2,3,4} {};
  void func1() { std::cout << "C1 4: " ; printvect(v1) ; std::cout << std::endl ;}
  C1<4> operator+(C1<4> &c2){
    C1<4> r;
    for(size_t iter1=0; iter1<4; ++iter1)
      r.v1[iter1]=v1[iter1]+c2.v1[iter1];
    return r;
  }
};

template <size_t N> class C1 {
  public:
  C1<4> BC;
  std::vector<int> v1;
  C1() {
      v1.resize(N-4);
      for(size_t iter1=0; iter1<N-4; ++iter1){
        v1[iter1]=5;
      }
  }
  void func1() { std::cout << "C1 N: "; printvect(BC.v1) ; printvect(v1) ; std::cout << std::endl ;}
  C1<N> operator+(C1<N> &c2){
    C1<N> r;
    r.BC=BC+c2.BC;
    for(size_t iter1=0; iter1<N-4; ++iter1)
      r.v1[iter1]=v1[iter1]+c2.v1[iter1];
    return r;
  }
};
int main() {
  C1<1> oc1; oc1.func1();
  C1<2> oc2; oc2.func1();
  C1<3> oc3a; oc3a.func1();
  C1<3> oc3b; oc3b.func1();
  auto oc3c=oc3a+oc3b;  oc3c.func1(); 
  C1<4> oc4; oc4.func1();
  C1<7> oc7a; oc7a.func1();
  C1<7> oc7b; oc7b.func1();
  auto oc7c=oc7a+oc7b;  oc7c.func1(); 
  return 0;
}

```

Output:
```
C1 1: 1 
C1 2: 1 2 
C1 3: 1 2 3 
C1 3: 1 2 3 
C1 3: 2 4 6 
C1 4: 1 2 3 4 
C1 N: 1 2 3 4 5 5 5 
C1 N: 1 2 3 4 5 5 5 
C1 N: 2 4 6 8 10 10 10 
```

**Comment by TallJimbo** [comment]
In C++11, I think it should be fairly straightforward to extend ndarray to > 8 dimensions, but I'm not quite ready to adopt C++11 features just yet as one of my main users (the project I work for) is still trying to support older compilers).  I expect that to change in the next year or so.

At the moment, while `makeVector` and initialization are indeed problems, the piece of code I'm more worried about is the view code, which relies on Boost.Fusion - and I think that has a limit hard-coded in as well.

Do you actually have a use case for higher than 8 dimensions?  If so, I think it'd be very easy to add a few more (just not infinite).

**Comment by hgkamath** [comment]
just penning thoughts, hth, i am sure you have thought about these things.

I think there are many scenarios that may involve arbitrary dimensions, like in probability and statistics. A joint probability over multiple discrete variables can be represented by a matrix, with each variable given its own dimension. the number discrete states in each variable becomes the length of a given dimension. Then marginalization and conditional calculations involve summing over, summing out and squeezing dimensions.

I am only in consideration phase. and am surveying. If C++11/14 features are taken advantage of then the programming might become intuitive, and can be made as in the popular matric programming languages.

1) Vector does not have to be a standalone type and can be a special case of a Array of one dimension. Its initialization can be done with initializer lists or stl::vector.
2) strides can be set to their default base don the size
3) the type can also be a default <double> and have a default initalizer.
4) the user should also not have to deal with the allocator also allocated at the same time as instantiation.  
5) rvalue and move semantics can be taken advantage of to avoid copies on argument passing. 
6) i did not see openmp preprocessing directives in the code. 

Array sizevect={2,3,2,3};
Array M1(sizevect,12.34);
auto M2=zeros(sizevect);
auto M3=M1+M2;
auto lambdafunc1=[&](x){2*x;}
auto M4=M3.apply(lambdafunc1); 
auto lambdafunc2=[&](w,x,y,z){4*w+x+sin(y)+log(z);}
auto M5=apply( vector<Array>{M1,M2,M3,M4},  lambdafunc2)

**Comment by hgkamath** [comment]
upon some experimentation, I speculate, the issue might be that as of C++14, still not possible to get the size of a brace-init-list as a constexpr at compile-time ??

**Comment by TallJimbo** [comment]
Closing as not relevant for this version of ndarray.  I'll consider these ideas if and when I ever get interested in writing a C++11/14/17 version.
