### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by nbecker** [ndarray/ndarray#44]
running /usr/bin/python3 /home/nbecker/scons/bootstrap.py --config=force --debug=stacktrace --with-boost-include=/home/nbecker/ndarray.new/../include --with-boost-lib=/home/nbecker/ndarray.new/../lib --with-eigen-include=/usr/include/eigen3 --prefix=/home/nbecker/ndarray.new/../.local tests CCFLAGS='-g -O3 -march=native' --boost-python-lib=boost_python3 2> tests.results

I got a number of failures.  Is this expected?

The file tests.results is 993k, should I put it somewhere?

**Comment by TallJimbo** [comment]
I have not been testing ndarray with Python 3, so I'm not totally surprised.  I have been planning to try to get that working with CMake instead of SCons, but I haven't gotten to it yet.

I suspect that most of the test.results file is warnings from Eigen (Eigen and gcc 6 do not like each other).  That's slated to be fixed in the next Eigen release, but in the meantime, could you try with the `squash-eigen-warnings` branch I've just pushed, in the hopes that that will get the `test.results` file down to the size where a human could inspect it?

**Comment by nbecker** [comment]
Both py2 and py3 are failing here:
/home/nbecker/ndarray.new/tests/ndarray.cc.test
Running 24 test cases...
sizeof(int): 4
sizeof(double*): 8
sizeof(shared_ptr<double>): 16
sizeof(Core<double,1>): 40
sizeof(Core<double,2>): 56
sizeof(Core<double,3>): 72
tests/ndarray.cc(93): error: in "allocation": check d.getStrides() == shape
has failed [(42,7,1,) != (5,6,7,)]
tests/ndarray.cc(96): error: in "allocation": check e.getStrides() == shape
has failed [(1,5,30,) != (5,6,7,)]
tests/ndarray.cc(100): error: in "allocation": check f.getStrides() ==
shape has failed [(42,7,1,) != (5,6,7,)]
tests/ndarray.cc(103): error: in "allocation": check g.getStrides() ==
shape has failed [(1,5,30,) != (5,6,7,)]

*** 4 failures are detected in the test module "ndarray"

other failures are on py3 due to PyConverter.h, which needs porting for py3
C api

On Tue, Jun 28, 2016 at 8:56 AM, Jim Bosch <notifications@github.com> wrote:

> I have not been testing ndarray with Python 3, so I'm not totally
> surprised. I have been planning to try to get that working with CMake
> instead of SCons, but I haven't gotten to it yet.
>
> I suspect that most of the test.results file is warnings from Eigen (Eigen
> and gcc 6 do not like each other). That's slated to be fixed in the next
> Eigen release, but in the meantime, could you try with the
> squash-eigen-warnings branch I've just pushed, in the hopes that that
> will get the test.results file down to the size where a human could
> inspect it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ndarray/ndarray/issues/44#issuecomment-229040553>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAHK0OFsq6pEIPEcHVDMU26TJ0H-EHxXks5qQRn1gaJpZM4I__61>
> .
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by TallJimbo** [comment]
Ah, that's some of the test code I just added.  Don't know how it slipped by me (apparently I really need to work on getting CI up and running).  That's fixed on master, now, and I've put the Eigen warning squashing on master too.

It may be a while before I get to updating PyConverter.h to Python 3, though.

**Comment by nbecker** [comment]
that's for swig, which I don't use.
You might find py3c useful

On Tue, Jun 28, 2016 at 9:19 AM, Jim Bosch <notifications@github.com> wrote:

> Ah, that's some of the test code I just added. Don't know how it slipped
> by me (apparently I really need to work on getting CI up and running).
> That's fixed on master, now, and I've put the Eigen warning squashing on
> master too.
>
> It may be a while before I get to updating PyConverter.h to Python 3,
> though.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ndarray/ndarray/issues/44#issuecomment-229046090>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAHK0Kc2ekZ4WFd_-B4QqGxIgIk_W7D5ks5qQR9VgaJpZM4I__61>
> .
>



-- 
*Those who don't understand recursion are doomed to repeat it*

**Comment by TallJimbo** [comment]
Thanks for the py3c tip; I suspect it's overkill for what I need to do, but we'll see.
