### ISSUE TITLE
code now failing on gcc-6.2.1

### ISSUE THREAD

**Issue by nbecker** [ndarray/ndarray#48]
```c++
template<typename flt_t>
nd::Array<flt_t,2,2> bit_llr_to_sym_ll (nd::Array<flt_t,1,1> intrlv_soft, nd::Array<int,2,2> llr_mask) {
  int BITS_PER_SYM = llr_mask.getShape()[1];
  int n_syms = llr_mask.getShape()[0];
  int syms_per_burst = intrlv_soft.getShape()[0]/BITS_PER_SYM;
  auto shape = nd::makeVector (syms_per_burst, BITS_PER_SYM);
  //  auto strides = nd::makeVector (BITS_PER_SYM, 1);
  //  auto w = nd::Array<flt_t,2,2> (nd::external (intrlv_soft.getData(), shape, strides, intrlv_soft.getManager()));
  auto w = nd::Array<flt_t,2,2> (nd::external (intrlv_soft.getData(), shape, nd::ROW_MAJOR, intrlv_soft.getManager()));
  nd::Array<flt_t,2,2> ll0 (w.getShape()); << failure here
```

This code used to compile, but not on gcc-6.2.1.  Passing w.getShape() to the constructor gives:
llr.cc:33:41: error: no matching function for call to 'ndarray::Array<float, 2, 2>::Array(ndarray::ArrayBase<ndarray::Array<float, 2, 2> >::Index)'

**Comment by TallJimbo** [comment]
I have to admit that I'm a bit stumped right now; `Array` has a constructor that takes `Vector<U,N>`, with `U` a template parameter, and `ArrayBase::Index` is a `Vector` with the same dimensions.  Does it work if you try some other constructor syntax?

**Comment by nbecker** [comment]
Appears I had used an old version of ndarray library (which lacked this constructor)
