### ISSUE TITLE
Please eliminate numpy deprecated API build warning

### ISSUE THREAD

**Issue by r-owen** [ndarray/ndarray#53]
Whenever I build something that uses ndarray I see the following warning:

numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]

It would be nice to eliminate the warnings, and fixing the problem may prevent eventual breakage.

**Comment by TallJimbo** [comment]
Made invalid by #63.
