### ISSUE TITLE
ndarray/converter/numpy.h uses values but doesn't include required header

### ISSUE THREAD

**Issue by nbecker** [ndarray/ndarray#60]
It appears values such as
npy_bool
are used, but are not defined unless the client code has

```
#include "numpy/arrayobject.h"
```
```
/home/nbecker/.local/include/ndarray/converter/numpy.h: In static member function 'static int ndarray::detail::NumpyTraits<bool>::getCode()':
/home/nbecker/.local/include/ndarray/converter/numpy.h:42:27: error: 'npy_bool' was not declared in this scope
  if (sizeof(bool)==sizeof(npy_bool)) return NPY_BOOL;
                           ^~~~~~~~
```

**Comment by TallJimbo** [comment]
That's always been the way with the stuff in `converter/` - the user is required to include the NumPy headers themselves.  This was originally to force them to do all of the per-file `#define` macros that are sometimes needed just before including those.  It's now less clear to me whether that's actually necessary to avoid symbol conflicts (as the NumPy docs claim), but changing it now would be a big backwards-incompatible interface change.

Note that this does not affect the Boost.Python converters at all (those go through an entirely different code path), and eventually we'd like to make that true for the pybind11 converters as well (but we haven't done that yet).
