### ISSUE TITLE
length 1 array matches scalar?

### ISSUE THREAD

**Issue by nbecker** [ndarray/ndarray#66]
I just noticed an undesirable and unexpected behavior.

I have 2 functions, 1 that matches a scalar, and 1 that matches an array.  The scalar function returns a scalar, and the array version returns array.

When called with an array of shape (1,), it appears the scalar function is matched (I say that because a scalar value is returned).

That isn't what I want or expect.  Perhaps that wouldn't happen if the scalar function was declared after the array version?

**Comment by TallJimbo** [comment]
I *suspect* the array function is actually the one being matched (if you could confirm that, that'd be great), and what's actually going on is a call to [`PyArray_Return()`](https://docs.scipy.org/doc/numpy-1.13.0/reference/c-api.array.html#c.PyArray_Return), is recommended by the NumPy docs for all functions returning arrays.  I've personally never liked that behavior either, but it seems like it's at least a moderately strong convention in the NumPy world.

It might be worth taking this to the NumPy mailling list, though, to see how much actual practice matches the recommendation in the docs.

**Comment by nbecker** [comment]
I don't think so - I switched the order of the declarations so that the
array match came first and my problem seems to be fixed - although I'm 100%
busy trying to get my app working ATM and I could be mistaken.

**Comment by TallJimbo** [comment]
Interesting; I was fairly certain that Boost.Python tries overloads in the *reverse* of the order in which they are declared, and goes with the first one that matches.  (I believe pybind11 does the opposite).

**Comment by nbecker** [comment]
I'm using pybind11

**Comment by TallJimbo** [comment]
Sounds like this is resolved, then; overload resolution is outside the control of ndarray, and I don't think there's much we can do besides require functions to be ordered in the appropriate way for the wrapper tool.

**Comment by nbecker** [comment]
My issue though is I didn't expect that an array of 1 element should match
a function that takes a scalar argument

**Comment by TallJimbo** [comment]
Hmm, yes, that is strange.  If you're using the pybind11 bindings, the first thing they do is call `PyArray_Check` on the input, and that certainly should not succeed on a scalar.

Can you post a minimal test case?

**Comment by nbecker** [comment]
It's the other way around : I passed a length 1 array, and it matched a
function that accepts a scalar.  At least, that's what I think happened.

**Comment by TallJimbo** [comment]
Ah, in that case I think it's pybind11 code that's not behaving as expecting, because that's what's providing the converter function for scalars.
