### ISSUE TITLE
compat with pybind11-2.3.0?

### ISSUE THREAD

**Issue by nbecker** [ndarray/ndarray#77]
I tried upgrading pybind11-2.2.3 -> 2.3.0.  Now I get:
```
/home/nbecker/.local/include/ndarray/pybind11.h:87:12: error: 'PYBIND11_DESCR' does not name a type; did you mean 'PYBIND11_EVAL'?
   87 |     static PYBIND11_DESCR name() { return type_descr(_<ndarray::Array<T,N,C>>()); }
      |            ^~~~~~~~~~~~~~
      |            PYBIND11_EVAL
```

**Comment by pkestene** [comment]
you can simply change that line with
```c++
static constexpr auto name = type_descr(_<ndarray::Array<T,N,C>>());
```

**Comment by nbecker** [comment]
While I can replace PYBIND11_DESCR at that line (and 2 others) as you suggest, compilation soon fails elsewhere, in pybind11/cast.h.  Has anyone else tried to use ndarray with pybind11-2.3.0?

**Comment by pkestene** [comment]
I works for me; I only had to change this one line.

if you want to cross-check, try this fork:
https://github.com/pkestene/ndarray/tree/issue77_pybind11_included

I slightly changed the top level CMakeLists.txt to download automatically pybind11 v2.3 just to be sure to use this version.

```shell
mkdir build; cd build
cmake -DNDARRAY_TEST:BOOL=ON -DNDARRAY_EIGEN:BOOL=ON -DNDARRAY_FFTW:BOOL=ON -DNDARRAY_PYBIND11:BOOL=ON ..
```

Here is the end of cmake configuration log (Ubuntu 18.04):
```text
(...)
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
-- pybind11 v2.3.dev1
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components: doxygen dot 
-- Found Boost: /usr/include (found version "1.65.1") found components: unit_test_framework 
-- Trying to find eigen in 
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found FFTW: /usr/include  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Found NumPy: version "1.13.3" /usr/lib/python3/dist-packages/numpy/core/include
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pkestene/install/python/ndarray/git/ndarray_pk/_build

```

**Comment by nbecker** [comment]
I'll save you from the LONG error message, but the gist is
```
/home/nbecker/.local/include/pybind11/cast.h:1900:56: error: no matching function for call to 'type_descr(pybind11::detail::descr<3, ndarray::Array<long unsigned int, 1, 1> > (&)())'
 1900 |     static constexpr auto arg_names = concat(type_descr(make_caster<Args>::name)...);
      |                                              ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~```

**Comment by pkestene** [comment]
It's hard to tell what is wrong here; maybe environment or compiler version problem ?
Could you try the fork to cross-check if you still have the error message ?

All I can tell is that the line change fixed the compilation for me.

**Comment by nbecker** [comment]
I can confirm that the branch origin/issue77_pybind11_included does fix my
compilation issues.

**Comment by pkestene** [comment]
cool ! I've submitted a PR for this small fix.

**Comment by pkestene** [comment]
Though, the pybind11_test fails while all other tests are ok.

The pybind11_test fails inside python with an internal error during loading the python module :
```python
In [1]: import pybind11_test_mod                                                                                                   
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-03baa2884630> in <module>
----> 1 import pybind11_test_mod

ImportError: Internal error while parsing type signature (2)

In [2]:   
```

**Comment by nbecker** [comment]
Yes, I just noticed that while my code compiled with the above patch, I'm getting ImportError on module loading just as stated above.

**Comment by dpaoliello** [comment]
FYI, I was able to workaround this error by changing the name to:
```
static constexpr auto name = _("ndarray::Array<") + t_conv::name + _(",") + _<N>() + _(",") + _<C>() + _(">");
```

Note that `t_conv` is defined at the top of the `type_caster` declaration (next to `Helper`) as:
```
using t_conv = make_caster<T>;
```

I'm not familiar enough with pybind to know if this is a reasonable workaround (I did model it after pybind's own names for STL containers).

**Comment by nbecker** [comment]
Can we finally have a PR that fully fixes this issue?  There are 2 required fixes, which are outlined above.

I see we have a PR for #77, but it is failing.  My guess is that we need to protect these 2 fixes with ifdefs based on pybind11 version (hopefully there is a way to tell the pybind11 version).

**Comment by TallJimbo** [comment]
I'll try to find some time to finally look at these this weekend. I've just been swamped and have had no time for outside-of-work development.  I think some of the Travis failures are affecting master, too - there just hasn't been any commits for a while there, and the build environment changed in the meantime.

**Comment by TallJimbo** [comment]
Thanks, all, for the debugging, the PR, and especially your patience.  ndarray master should now be compatible with pybind11 2.3+ (tested with 2.5).  I'll be tagging a release shortly.

For the curious, it looks like all of the trouble with getting the right C++ type into the pybind11 `_descr` compile-time string class was just beside the point: pybind11 really wanted a Python type there, and just giving it "numpy.ndarray" seems to sidestep a lot of those problems.
