### ISSUE TITLE
need fftw3？

### ISSUE THREAD

**Issue by nickhuangxinyu** [ndarray/ndarray#96]
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:843 (message):
  None of the required 'fftw3' found
Call Stack (most recent call first):
  tests/CMakeLists.txt:40 (pkg_search_module)

i saw fftw is a fourier transformation library, is it neccessary?

**Comment by TallJimbo** [comment]
FFTW is optional.  You should be able to build without it by passing `-DNDARRY_FFTW=OFF` to `cmake`.

**Comment by nickhuangxinyu** [comment]
but i think tests need fftw
